# Generated by Django 4.2.7 on 2023-11-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
